### ISSUE TITLE
Discrete action

### ISSUE THREAD

**Issue by Bruce-Lan-ZY** [Lizhi-sjtu/MARL-code-pytorch#3]
(MARL) root@5e4fd369caa6:~/code/MARL-code-pytorch/4.MADDPG_MATD3_MPE# python3 MADDPG_MATD3_main.py --algorithm MADDPG
Traceback (most recent call last):
  File "MADDPG_MATD3_main.py", line 142, in <module>
    runner = Runner(args, env_name=env_names[env_index], number=1, seed=0)
  File "MADDPG_MATD3_main.py", line 19, in __init__
    self.env = make_env(env_name, discrete=False)  # Continuous action space
TypeError: make_env() got an unexpected keyword argument 'discrete'
 
Then, I try to remove this argument'discrete' ------self.env = make_env(env_name). There appear this problem:

(MARL) root@5e4fd369caa6:~/code/MARL-code-pytorch/4.MADDPG_MATD3_MPE# python3 MADDPG_MATD3_main.py --algorithm MADDPG
Traceback (most recent call last):
  File "MADDPG_MATD3_main.py", line 142, in <module>
    runner = Runner(args, env_name=env_names[env_index], number=1, seed=0)
  File "MADDPG_MATD3_main.py", line 23, in __init__
    self.args.action_dim_n = [self.env.action_space[i].shape[0] for i in range(self.args.N)]  # actions dimensions of N agents
  File "MADDPG_MATD3_main.py", line 23, in <listcomp>
    self.args.action_dim_n = [self.env.action_space[i].shape[0] for i in range(self.args.N)]  # actions dimensions of N agents
 IndexError: tuple index out of range

Could anyone help me?

**Comment by air-tea** [comment]
I also met this problem, have you solved it?

**Comment by Bruce-Lan-ZY** [comment]
No, I used other repos.

**Comment by air-tea** [comment]
Is it convenient for you to tell me which repos you use? Thank you!

**Comment by wydxry** [comment]
You should add multiagent and change make_env.py about discrete

**Comment by air-tea** [comment]
Got it, Thanks for your answering~

**Comment by weiyu0258** [comment]
I  remove the argument 'discrete'，and then change the  multiagent-particle-envs-master\multiagent\environment\self.discrete_action_input = True,  the code run successfully
